version: '4.28'

services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tramites
    volumes:
      - tramites_pg_data:/bitnami/postgresql

volumes:
  tramites_pg_data: